# column_desc.py
COLUMN_DESC = {
    'acoq': "Current Assets - Other - Total",
    'actq': "Current Assets - Total",
    'apq': "Account Payable/Creditors - Trade",
    'atq': "Assets - Total",
    'ceqq': "Common/Ordinary Equity - Total",
    'epsfiq': "Earnings Per Share (Diluted) - Including Extraordinary Items",
    'ibadjq': "Income Before Extraordinary Items - Adjusted for Common Stock Equivalents",
    'invtq': "Inventories - Total",
    'niq': "Net Income (Loss)",
    'rectq': "Receivables - Total",
    'saleq': "Sales/Turnover (Net)",
    'txpq': "Income Taxes Payable",
    'prccq': "Price Close - Quarter",
    'prclq': "Price Low - Quarter",
    'cheq': "Cash and Short-Term Investments",
    'cogsq': "Cost of Goods Sold",
    'dlcq': "Debt in Current Liabilities",
    'dlttq': "Long-Term Debt - Total",
    'dvpq': "Dividends - Preferred/Preference",
    'epspxq': "Earnings Per Share (Basic) - Excluding Extraordinary Items",
    'ibq': "Income Before Extraordinary Items",
    'lctq': "Current Liabilities - Total",
    'opepsq': "Earnings Per Share from Operations",
    'revtq': "Revenue - Total",
    'tstkq': "Treasury Stock - Total (All Capital)",
    'xoprq': "Operating Expense - Total",
    'prchq': "Price High - Quarter",
}
